#!/usr/bin/env bash

# https://felixkratz.github.io/SketchyBar/config/bar
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
# https://felixkratz.github.io/SketchyBar/config/items
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="${CONFIG_DIR}/plugins"
ITEM_DIR="${CONFIG_DIR}/items"

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

FONT="SF Pro"
PADDINGS=3

launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color="$ICON_COLOR"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
  label.font="$FONT:Semibold:13.0"
  label.color="$LABEL_COLOR"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  padding_right="$PADDINGS"
  padding_left="$PADDINGS"
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

### LEFT ###
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/mail.sh"

### RIGHT ###
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"

sketchybar --update
